name: rl3
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pytorch
  - cudatoolkit
  - absl-py
  - pyparsing
  - jupyter
  - scikit-image
  - pip:
    - termcolor
    - dm_control
    - git+git://github.com/denisyarats/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - pandas
    - ipdb
    - tqdm
    - torchvision
    - yapf
    - mujoco_py==2.0.2.8
    - scikit-learn
    - matplotlib
    - kornia
    - opencv-python
    - scikit-video
    - gym==0.19.0
